views.style.maps_twelvestepmeeting:
  type: views_style
  label: 'Geolocation Twelve Step Meeting Map'
  mapping:
    geolocation_field:
      type: string
      label: 'Geolocation Field'
    title_field:
      type: string
      label: 'Title Field'
    centre:
      type: sequence
      label: 'Centre Option'
      sequence:
        type: mapping
        mapping:
          weight:
            type: integer
            label: 'Weight'
          enable:
            type: boolean
            label: 'enable'
          settings:
            type: sequence
            label: 'Settings'
            sequence:
              type: string

views.row.fields_twelvestepmeeting:
  type: views_row
  label: 'Twelve Step Meeting Field options'
  mapping:
    default_field_elements:
      type: boolean
      label: 'Provide default field wrapper elements'
    inline:
      type: sequence
      label: 'Inline'
      sequence:
        type: string
        label: 'Inline'
    separator:
      type: string
      label: 'Separator'
    hide_empty:
      type: boolean
      label: 'Hide empty'
